import type { Metadata } from "next";
import { Cinzel, Poppins} from "next/font/google";
import "@/styles/globals.css";
import SmoothScroll from "@/components/ui/SmoothScroll";
import Header from "@/components/layout/Header";

const styleFont = Cinzel({
  variable: "--font-style",
  subsets: ["latin"],
});

const textFont = Poppins({
  variable: "--font-text",
  subsets: ["latin"],
  weight:["100", '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "1% Lounge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${styleFont.variable} ${textFont.variable} font-text antialiased`}
      >
        <Header/>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
